
import os
import psycopg2
import polars as pl
import phiOp as po
import op2python as o2p
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    tuples = cur.fetchall()
    cur.close()
    conn.close()
    
    df = pl.DataFrame(tuples, {'cust': pl.String, 'prod': pl.String, 'day': pl.Int32, 
                              'month': pl.Int32, 'year': pl.Int32, 'state': pl.String, 'quant': pl.Int32, 'date': pl.Date})
    
    
    # THIS IS WHERE THE GENERATED CODE GOES!
    phi = po.parse_query('''select cust, prod, sum(X.quant), sum(Y.quant), sum(Z.quant)
from sales
group by cust, prod: X, Y, Z
suchthat X.state = 'NY', Y.state = 'NJ', Z.state = 'CT'\n''')
    
    opInstance = o2p.op2python(phi)
    
    body = opInstance.construct_queries(df)
    
    return body

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    